### ISSUE TITLE
segment error

### ISSUE THREAD

**Issue by SunshineDou** [HTLife/png_to_klg#11]
Hi,
I want to convert dataset png to klg, I used the rgbd_dataset_freiburg3_long_office_household dataset, first I used the associate.py to generate associations.txt, then I convert, but it failed, this is the output error:
Current working directory:
	/home/png_to_klg/build/rgbd_dataset_freiburg3_long_office_household
段错误 (核心已转储)

what is the problem? thank you very much

**Comment by HTLife** [comment]
It may caused by the wrong order of the path.
In association file, depth sould appear first.

**Comment by SunshineDou** [comment]
Thank you very much for your reply. I have been confused by this problem during these days
according to your reply, I checked the associations.txt, depth appears first in the file as follows:
1341847980.723020 depth/1341847980.723020.png 1341847980.722988 rgb/1341847980.722988.png
1341847980.754755 depth/1341847980.754755.png 1341847980.754743 rgb/1341847980.754743.png
1341847980.786879 depth/1341847980.786879.png 1341847980.786856 rgb/1341847980.786856.png
1341847980.822989 depth/1341847980.822989.png 1341847980.822978 rgb/1341847980.822978.png
 after generating the associations.txt, I type in the command:
./png2klg -w '/home/workspace/png_to_klg/build/freihousehold/' -o '/home/lutao/png_to_klg/build/freihousehold/output.klg'

but it still failed. what's the problem?

**Comment by SunshineDou** [comment]
Even when I run the sample dataset "livingroom_kt0_rs" . the result is the same. like this:
Current working directory:
	/home/workspace/png_to_klg/living_room_kt0_rs
段错误 (核心已转储)

**Comment by HTLife** [comment]
Try absolute path

**Comment by HTLife** [comment]
You may run the program under debug mode, and find out what's happening.

**Comment by SunshineDou** [comment]
Thanks again for your reply. I will try to run it under debug mode later to find out the problem. just now I stalled the png_to_klg-docker on ubuntu, which can get correct result.
