### ISSUE TITLE
Realsense Dataset

### ISSUE THREAD

**Issue by SunshineDou** [HTLife/png_to_klg#12]
Hello,
I succeeded in converting the TUM dataset, but I want to make some dataset using Realsense, so I record 100 depth and color png images by realsense, the associations.txt file like this:
1 depth/1.png 1 rgb/1.png
2 depth/2.png 2 rgb/2.png
3 depth/3.png 3 rgb/3.png
4 depth/4.png 4 rgb/4.png
5 depth/5.png 5 rgb/5.png
6 depth/6.png 6 rgb/6.png
7 depth/7.png 7 rgb/7.png
8 depth/8.png 8 rgb/8.png

and then I use this code to convert it to klg format.
but problem occurred.
the result is as follows:
Current working directory:
	/input-output/dataset1
Depth: depth/99.png
RGB: rgb/99.png
scale: 5000
klg_name:
	/input-output/dataset1.klg
Progress:
Conversion complete!
although it said "Conversion complete" but the output klg file is only 4 bytes. and I cannot run ElasticFusion with the converted klg dataset.

what is the problem?

**Comment by HTLife** [comment]
It might be path related problem.  For example, the program fail to read the image.

**Comment by SunshineDou** [comment]
Thanks for your patient explanation. but I think the might should be right as I have tried to convert the "living_room"dataset in that way, but it succeeded. I have a question that the associations file must in ascending order just like this:
1 depth/1.png 1 rgb/1.png
2 depth/2.png 2 rgb/2.png

that we don't have to generate it by associate.py, is it right?
the second question is that whether the number of images have limitations or not? as I only take 100 depth images and 100 rgb images, will it be too small?

thanks again for your replying!

**Comment by SunshineDou** [comment]
I have succeeded in converting it into klg format, as I was careless to name the folder"rgb" to "color" when I changed it to "rgb" , it succeeded in converting it to klg format. but I have tried to run with it in Elasticfusion, but I stilled failed. The outcome is:

segmentation error
段错误 (核心已转储)

**Comment by HTLife** [comment]
Check TUM rgbd dataset and see if your folder structure is different from it or not.
