### ISSUE TITLE
Not a JPEG file: starts with 0×2f 0×30

### ISSUE THREAD

**Issue by omaar97** [HTLife/png_to_klg#13]
Hello all,
I'm having this error when trying to run another generated .klg file using ElasticFusion:

> Not a JPEG file: starts with 0×2f 0×30

I tried freiburg1desk dataset and it works fine. I've checked similar issues and tried the answered solutions but nothing worked. Here are some lines from my associations.txt:

> 0.011110 depth/frame0.png 0.011110 rgb/frame0.png
> 0.016520 depth/frame1.png 0.016520 rgb/frame1.png
> 0.021930 depth/frame2.png 0.021930 rgb/frame2.png
> 0.027340 depth/frame3.png 0.027340 rgb/frame3.png
> 0.032750 depth/frame4.png 0.032750 rgb/frame4.png
> 0.038160 depth/frame5.png 0.038160 rgb/frame5.png
> 0.043570 depth/frame6.png 0.043570 rgb/frame6.png
> 0.048980 depth/frame7.png 0.048980 rgb/frame7.png
> 0.054390 depth/frame8.png 0.054390 rgb/frame8.png
> 0.059800 depth/frame9.png 0.059800 rgb/frame9.png
> 0.065210 depth/frame10.png 0.065210 rgb/frame10.png
> 0.070620 depth/frame11.png 0.070620 rgb/frame11.png
> 0.076030 depth/frame12.png 0.076030 rgb/frame12.png
> 0.081440 depth/frame13.png 0.081440 rgb/frame13.png

I think I correctly followed the steps to create the .klg (otherwise I don't think the frieburg1desk dataset would've worked). What could be wrong here? Thanks.

**Comment by omaar97** [comment]
@HTLife Could you please help?

**Comment by HTLife** [comment]
It seems that your file is not in the right format.
> Not a JPEG file: starts with 0×2f 0×30

**Comment by omaar97** [comment]
depth & RGB images are in .png as below, associations is in .txt. What other things could go wrong? I'm generating the images from MATLAB on Windows 10 and then I use them on Ubuntu, is it possible that image generation using MATLAB causes the error?! 

![daaa](https://user-images.githubusercontent.com/44803875/51088141-f967ab00-1764-11e9-81df-47750af0fa76.jpg)

**Comment by HTLife** [comment]
JPEG should start with 0xFF
PNG should start with 0x89

**Comment by omaar97** [comment]
Sorry I don't get it. Shouldn't the depth & RGB images be in .png format? I checked mine and they both start with 0x89 so they are surely in .png format. Is png_to_klg not recognizing them as .png images?

**Comment by HTLife** [comment]
I said that is because of your error report:
>Not a JPEG file: starts with 0×2f 0×30

If the file format is correct, could you check the file size?  Sometimes, it's just some working directory related problem.

**Comment by omaar97** [comment]
I resized the images to 640×480, the error disappeared but now it gives me 
> segmentation error (core dumped)

I'm checking similar issues but none of the solutions for it seems to work. Do you have any idea about it? Thanks.

**Comment by HTLife** [comment]
Run with debug mode and see which line is the cause of this problem.

**Comment by omaar97** [comment]
Thank you, I solved it.
Bit depth for depth images should be 16 bit, mine was 24, I changed it to 16 and it ran successfully.

**Comment by HTLife** [comment]
Congratulations 
I’m glad to hear that
