### ISSUE TITLE
Segmentation fault with my klg on ElasticFusion

### ISSUE THREAD

**Issue by scipione1** [HTLife/png_to_klg#14]
So, I used png_to_klg to obtain a dataset to run with ElasticFusion. The dataset was collected with the Realsense D435i sensor. Even though png_to_klg says that the conversion was successful, when I run the klg with ElasticFusion I get segmentation fault. However, I'm a 100% sure I'm doing it right, because I also tried to convert the TUM dataset (and ICL-NUIM) and it worked on ElasticFusion.
Then, I discovered that the TUM dataset is collected with a Kinect and that the depth images produced by the Realsense and the Kinect are different, as you can see in the images below.

Realsense: ![rs-save-to-disk-output-depth45](https://user-images.githubusercontent.com/32809427/51399455-4fae6280-1b46-11e9-832c-4be5b348701a.png)

TUM: ![1305031453 374112](https://user-images.githubusercontent.com/32809427/51399802-1b877180-1b47-11e9-8962-31a22d5cf6e2.png)

So, is there a way to create a functioning klg for ElasticFusion with this converter using a dataset produced by the Realsense?

Thank you.

**Comment by HTLife** [comment]
Realsense is using different bit size to represent the depth.
You can convert your depth image to TUM format, then adopt the same program.

**Comment by scipione1** [comment]
Thank you! Can you please tell me how to do it?

**Comment by scipione1** [comment]
TUM wants 16bit monochrome images. So what I have done so far is:

```
cvtColor(depth,depth,COLOR_BGR2GRAY); // 3 to 1 chan
depth.convertTo(depth, CV_16U, 255); // 8bit to 16
```
Indeed, I get this kind of images:
![rs-save-to-disk-output-depth8](https://user-images.githubusercontent.com/32809427/51468701-e447d900-1d6f-11e9-81ef-d3b3b58420fb.png)

However, elasticFusion still gives segmentation fault.

**Comment by scipione1** [comment]
Just managed to run Elastic Fusion. You need to resize both depth and RGB images to 640x480.

**Comment by Viky397** [comment]
Hello, I did resize both my depth and RGB images to 640x480 but still get the Segmentation fault error. Do you have any other tips?

**Comment by Darker-zq** [comment]
> 
hello, I recently encountered the same problem as you.could I get your code of  collect data using camera.  This is my email(01170218@cumt.edu.cn).Thank you very much.
