### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bomtorazek** [HTLife/png_to_klg#16]
I typed the following sentence

./pngtoklg -w '/home/username/Downloads/pngtoklg/build/living_room_traj0_frei_png/' -o 'home/username/Downloads/pngtoklg/build/living_room_traj0_frei_png/liv.klg' -s 0.0002
--------------------------------------------------------------------------------------------------------------------
and I got

Current working directory:
	/home/username/Downloads/pngtoklg/build/living_room_traj0_frei_png
Depth: depth/1508.png
RGB: rgb/1508.png
scale: 0.0002
klg_name:
	home/username/Downloads/pngtoklg/build/living_room_traj0_frei_png/liv.klg
Segmentation fault (core dumped)
--------------------------------------------------------------------------------------------------------------------
How can I fix it? Thanks

**Comment by bomtorazek** [comment]
I resolve with "sudo su"

**Comment by HTLife** [comment]
Your files might have some permission problems.
Resolve it by `chown` or `chmod `
