### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by roliveiradoteu** [HTLife/png_to_klg#2]
Hi,
I created the liv.klg as suggested but when i try to use it in Kintinuous i get :

> CloudSliceProcessorThread started
> Segmentation fault (core dumped)

Likewise ElasticFusion troughs a Segmentation fault (core dumped), even using the -d 12 -c 3 -f

Any clues?

**Comment by HTLife** [comment]
@roliveiradoteu Have you ever successfully create any .klg file?  For example, from TUM or ICL-NUIM.
The clue you provided is not enough for debugging.
What's your source file image size? (640*480 is expected both for RGB and D)
The numbering of your images might affects.
Faster way is to run all code under debug mode, and trace to the line that lead to crash.

**Comment by roliveiradoteu** [comment]
Hi,

Yes I created the livingroom_kt0_rs which is what I am trying to run (answers 2nd question as well about the resolution)

I can run the http://www.cs.nuim.ie/research/vision/data/loop.klg in Elastic Fusion just fine. It is when i try  liv.klg that i have issues. 

Debug is bellow

> roliveira@T440p:~/Software/ElasticFusion/GUI/build$ gdb -ex=r --args ./ElasticFusion -l liv.klg -d 12 -c 3 -f
...
Starting program: /home/roliveira/Software/ElasticFusion/GUI/build/ElasticFusion -l liv.klg -d 12 -c 3 -f
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe2ef4700 (LWP 3997)]
[New Thread 0x7fffe26f3700 (LWP 3998)]
[New Thread 0x7fffe1ef2700 (LWP 3999)]
warning: Can't attach LWP 1572887: No child processes
/build/buildd/gdb-7.7.1/gdb/linux-thread-db.c:434: internal-error: thread_get_info_callback: Assertion `inout->thread_info != NULL' failed.

**Comment by roliveiradoteu** [comment]
The file I create from your sequence is ~16 MB (16,412,752 bytes), not the suggested 3.2Mb

File is uploaded to https://ufile.io/b54cf if you want to try

I am using opencv 2.4.8, I modified CMakeLists.txt

[https://github.com/roliveiradoteu/png_to_klg/blob/master/CMakeLists.txt](url)

**Comment by HTLife** [comment]
Thanks I will find some time to deal with this bug before weekend.

**Comment by roliveiradoteu** [comment]
@HTLife any luck?

**Comment by HTLife** [comment]
@roliveiradoteu 
You could download the file provided by ICL-NUIM directly.
https://www.doc.ic.ac.uk/~ahanda/VaFRIC/iclnuim.html
(Living Room 'lr kt0') => (TUM RGB-D Compatible PNGs)
And it contains associations.txt already.

**Comment by HTLife** [comment]
@roliveiradoteu  I update instructions in README.md, which is showing on project home page.
Should work well now.

**Comment by quanqhow** [comment]
@HTLife  Dear Jacky, what is your email address, I got trouble in running your program.

**Comment by HTLife** [comment]
@quanqhow  You could contact me by jjkka.132@gmail.com

**Comment by Godpeterliu** [comment]
@HTLife  when I run the elasitcfunsion by the .klg created by your program, my computer will be down, but the klg provided by elasitcfunsion will not

**Comment by HTLife** [comment]
@Godpeterliu  Please provide the file name that you used, and double check it with sha1 checksum file.
I just test all TUM file and with no problem.
