### ISSUE TITLE
Will it work with any set of depth maps or only with TUM data set?

### ISSUE THREAD

**Issue by mavbot66** [HTLife/png_to_klg#5]
Hi...as per your suggestion at https://github.com/mp3guy/ElasticFusion/issues/121
I looked at your project png_to_klg. I think this will serve my purpose of building 3D point cloud offline from pre-recorded depth maps.But is it that png_to_klg data will work only for TUM data set? or it can work for any depth map captured with kinect?

**Comment by HTLife** [comment]
TUM used kinectv1 to record their dataset.  If you are using v1 that would be convenient.  If you are using v2 some parameters need to be adjust.  Image width, height, depth factor...its recommended to convert it to fit TUM’s format.

TUM format.(https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats)

**Comment by mavbot66** [comment]
Hi...png_to_klg works fine with the downloaded TUM data set. I am capturing with kinect1 and able to save the depth maps as monochrome 16 bit. Just wanted to clarify whats with this depth.txt and rgb.txt. format. As explained I can record them (depth and rgb) as a temporal sequence and number the time sequence in increasing order. TUM had very specific syntax in the depth and rgb text files. Do we need to exactly replicate the TUM data set syntax to get a proper associations.txt file ? or in other words can we generate the compatible rgb.txt and depth.txt automatically?

**Comment by HTLife** [comment]
You don't need to follow the naming convention.  Any file name is ok.
The depth.txt and rgb.txt is just file lists to make associations.txt.  (When you capture the rgb and depth image, the timing will not be exactly the same.   associate.py help you to associate the time.)

However, if you don't need this association function.
You could just generate the associations.txt by yourself.
And the format is  (set both the depth and rgb time to be the same is fine)

(time) (depth file path) (time) (rgb file path)
```
0.033333 ./depth/scene_00_0000_rs.png 0.033333 ./rgb/scene_00_0000_rs.png
0.066666 ./depth/scene_00_0001_rs.png 0.066666 ./rgb/scene_00_0001_rs.png
0.099999 ./depth/scene_00_0002_rs.png 0.099999 ./rgb/scene_00_0002_rs.png
0.133332 ./depth/scene_00_0003_rs.png 0.133332 ./rgb/scene_00_0003_rs.png
0.166665 ./depth/scene_00_0004_rs.png 0.166665 ./rgb/scene_00_0004_rs.png
0.199998 ./depth/scene_00_0005_rs.png 0.199998 ./rgb/scene_00_0005_rs.png
```

**Comment by elliestath** [comment]
I am working with the ICL-NUIM dataset, but I keep getting a corrupted .klg file with the size of 4 bytes, although I run as you say the following command 

`./pngtoklg -w '../living_room_traj0_frei_png/' -o 'living_room_traj0.klg'`

and I get as a result
`Progress:
Conversion complete!`

I tried it with two different TUM datasets and I keep getting the same error.
.klg file contains nothing but some characters in one line, what may be wrong?

**Comment by HTLife** [comment]
Did you generate the associations.txt file yet?
tum data set should use the parameter -t

**Comment by elliestath** [comment]
I used the associations.txt file as it was provided in the dataset, didn't generate it myself. It seems that it is ok for this, as it can locate it in the right path.
I am using the ICL-NUIM dataset, so I didn't use the -t parameter

**Comment by HTLife** [comment]
@elliestath One possible reason is that you have to download "TUM RGB-D Compatible PNGs".

I just tested on ICL-NUIM  Living Room 'lr kt0' (TUM RGB-D Compatible PNGs) and successfully generate the correct klg file.

Could you provide the full message output from png_to_klg?

**Comment by HTLife** [comment]
@elliestath 
If you still can't find the source of the problem, here I provide the files that I converted.

ftp://rvlslam.csie.io/KLG_ElasticFusion/ICLNUIM/
or
https://drive.google.com/drive/folders/1nen4wcKzB1PKhz9MiA13rPCS0QzOMwBU?usp=sharing

**Comment by elliestath** [comment]
@HTLife 
Thanks! These klg files do work on ElasticFusion.

The full output of png_to_klg is a s following, there seemed to be no problem, however, the written .klg file was empty.

![screenshot from 2018-01-03 12-17-12](https://user-images.githubusercontent.com/11046400/34518671-b7513418-f080-11e7-8000-a047a56bcc2a.png)

**Comment by edith-langer** [comment]
Hi,

I have the exact same problem. All the klg files I try to create are only 4 Bytes, although the output says "conversion complete". Also the livingroom test case produces a 4 Byte klg-file. I am not interested in the TUM or ICL-NUIM, so I can not use the files you already created. Any ideas what could go wrong?

Update:
After some debugging, I figured out that the problem are the img file paths!

**Comment by HTLife** [comment]
@edith-langer Could you provide your associations file? (Just several lines)
