### ISSUE TITLE
Not a JPEG file: starts with 0x15 0xe5

### ISSUE THREAD

**Issue by ywcmaike** [HTLife/png_to_klg#6]
hi，gay!
I compiled your project and get the .klg. but when I run the elasticfusion, it makes no sense. I think elasticfusion maybe support the jpeg file format only. TUM dataset is composed of png, but the elasticfusion needs jpeg.

my method is as followed:
~/work/ElasticFusion/GUI/build$ ./ElasticFusion -l /home/yeweicai/Downloads/dataset/TUM/rgbd_dataset_freiburg2_desk/fr2desk.klg -d 12 -c 3 -f
Not a JPEG file: starts with 0x15 0xe5

I want to know how you can run the elasticfusion.  Should I write the support of png for elasticfusion to use the png file format?  And can you give me your method to run the elasticfusion with the png? I want your help. I am the beginner of slam and 3D Reconstruction (such as Elasticfusion). 

you can email me 2755289083@qq.com 
thanks all.

**Comment by ywcmaike** [comment]
@HTLife

**Comment by HTLife** [comment]
@ywcmaike 
Have you ever tried the file that I converted?

**Comment by ywcmaike** [comment]
Hi,  I have done like what you do. but the elasticfusion runs error.  I read the code of elasticfusion, only have jpegloader.h, but no pngloader.  it may be the reason.   I can't get the file that you converted.  I'm Chinese in mainland, can not surf the internet such like "https://drive.google.com" quickly.    Do you have the pan.baidu.com?

**Comment by HTLife** [comment]
Try this [link](http://140.123.106.110/tum/rgbd_dataset_freiburg1_360.klg) out!

**Comment by ywcmaike** [comment]
I try the dataset you have given, and it can run normally. But when I do as the README.md that you said, the producted klg doesnot work in the elasticfusion. I always crashed with the error such as "Not a JPEG file: starts with 0x15 0xe5" . How to produce the klg?   What I do is as followed:
1) product the associations.txt
~/Downloads/dataset/TUM/rgbd_dataset_freiburg1_360$ python associate.py rgb.txt depth.txt > associations.txt
2) product the klg file:
~/work/3dReconstruction/png_to_klg/build$ ./pngtoklg -w ~/Downloads/dataset/TUM/rgbd_dataset_freiburg1_360/ -o ~/Downloads/dataset/TUM/rgbd_dataset_freiburg1_360.klg -t

Current working directory:
	/home/yeweicai/Downloads/dataset/TUM/rgbd_dataset_freiburg1_360
Depth: rgb/1305031815.817442.png
RGB: depth/1305031815.803102.png
scale: 5000
klg_name:
	/home/yeweicai/Downloads/dataset/TUM/rgbd_dataset_freiburg1_360.klg
Progress:
0744 / 0744
Conversion complete!
3) run the elasticfusion:
~/work/ElasticFusion/GUI/build$ ./ElasticFusion -l ~/Downloads/dataset/TUM/rgbd_dataset_freiburg1_360.klg 
Not a JPEG file: starts with 0x00 0x1f
It ran and crashed quikly with the error :Not a JPEG file: starts with 0x00 0x1f
@HTLife

**Comment by HTLife** [comment]
In step `product the associations.txt`, depth should be the first parameter.
```
python associate.py PATH_TO_SEQUENCE/depth.txt PATH_TO_SEQUENCE/rgb.txt > associations.txt
```

**Comment by ywcmaike** [comment]
1) python associate.py depth.txt rgb.txt > associations.txt

thanks, I have solved the problem, and it can run in the elasticfusion well.
I close the issue.
