### ISSUE TITLE
Not a JPEG file: starts with 0x15 0xe5

### ISSUE THREAD

**Issue by ajithkrishnan** [HTLife/png_to_klg#9]
Hi,

First off, thanks a lot for this repo. I was able to convert the TUM freiburg2_desk dataset to .klg format using your code. However when i try to run it with ./ElasticFusion -l /home/s/png_to_klg/rgbd_dataset_freiburg2_desk/freiburg2.klg -d 12 -c 3 -f, I get the following error:
Not a JPEG file: starts with 0x15 0xe5

Is there a way to make it accept PNG source files instead of JPEG?

Thanks in advance.

**Comment by HTLife** [comment]
You might need to modify the JPEG related code in ElasticFusion directly.

**Comment by ajithkrishnan** [comment]
Hey,
Thanks for responding. I figured out the error. I had used your **associate.sh** script to generate the associations.txt file. The order of the paths to **rgb.txt** and **depth.txt** files are wrong. I swapped it and it works now :)

**Comment by HTLife** [comment]
Great!!
